openapi: 3.1.0
info:
  title: Reezonly Space Platform API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  description: |
    **Руководство интеграций Reezonly Space** — это главный источник информации, благодаря которому внешние CRM, CMS, ERP и маркетинговые системы быстро подключают программный доступ к Space API.

    Здесь собраны схемы аутентификации, бизнес‑блоки пользователей, групп, курсов, сертификатов и отчетов, примеры запросов и схемы ответов. Документация рассказывает, как синхронизировать пользователей, подтянуть группы и права из вашей CRM, создавать курсы и выгружать отчеты — все через безопасный `X-API-Key` и понятные бизнес-сущности.

    ## Что можно делать через API

    - Добавлять, изменять и удалять пользователей.
    - Назначать пользователям обучение.
    - Создавать группы, редактировать их и назначать им обучение.
    - Изменять пользовательские поля.
    - Выдавать сертификаты после завершения обучения.

    ## Аутентификация

    Для доступа к API необходимо использовать **API Key** в заголовке запроса:

    ```
    X-API-Key: your_api_key_here
    ```

    ## Базовый URL

    ```
    https://your-space-domain.com/api/v1
    ```

servers:
  - url: https://your-space-domain.com/api/v1
    description: Production server
  - url: https://staging-space-domain.com/api/v1
    description: Staging server

x-servers:
  - url: https://your-space-domain.com/api/v1
    description: Production
  - url: https://staging-space-domain.com/api/v1
    description: Staging
  - url: http://localhost:8080/api/v1
    description: Local

security:
  - ApiKeyAuth: []

tags: []

paths: {}

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer token authentication (JWT)
  schemas: {}
  parameters: {}
  responses: {}
