# Learning API - 4 метода (READ-ONLY)
# Страницы и курсы (только чтение)

openapi: 3.1.0
info:
  title: Learning API
  version: 1.0.0
  description: |
    ## Pages and Courses (Learning Products) — 4 метода (READ-ONLY)

    Раздел Learning предоставляет доступ к каталогу курсов и страниц контента в режиме чтения. Основной контент курсов хранится во внешней LMS системе, а Space выступает как витрина и система управления доступом.

    **⚠️ Важно:** Эти методы доступны только для чтения. Изменение контента курсов и уроков выполняется через LMS, а не через этот API.

tags:
  - name: Courses
    description: |
      ## Курсы и обучающие продукты (только чтение)

      **Назначение:** предоставить актуальные метаданные курсов и продуктов для внешних витрин, маркетинговых страниц и CRM.
      **Ключевые особенности:** постраничная выдача (`/course/course/index`), подробные описания структуры и уроков, атрибуты активности (`students_count`, `enabled`, `status`, `picture`, `lms_id`).
      **Пример Use case:** маркетинговая команда из внешнего CMS подгружает `/course/course/index`, показывает список продуктов с картинками и вызывает `/course/course/view` для раскрытия программы и уроков.

  - name: Pages
    description: |
      ## Страницы и контент сайта (только чтение)

      **Назначение:** раскрыть структуру публичных и закрытых страниц сайта, чтобы сторонние CMS могли отображать лендинги и меню.
      **Ключевые особенности:** подробный список типов страниц (`/dictionary/dictionary/page-types`), фильтруемая выдача `pages`, статус `enabled`, SEO-метаданные, `alias` и `category`.
      **Пример Use case:** внешняя система заимствует SPA-меню, вызывает `/dictionary/dictionary/pages`, сортирует по типу и обновляет ссылки на новом сайте без доступа к внутреннему CMS.

paths:
  # === Courses ===

  /course/course/index:
    get:
      tags: [Courses]
      summary: Получить каталог курсов
      description: Возвращает список доступных курсов с базовой информацией (только чтение)
      parameters:
        - $ref: './core/common/parameters.yaml#/components/parameters/Page'
        - $ref: './core/common/parameters.yaml#/components/parameters/PerPage'
        - name: category_id
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
          description: Фильтр по ID категории курсов
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [active, inactive, archived]
            default: active
          description: Фильтр по статусу курса
        - name: featured
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: Показать только рекомендуемые курсы
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                            description:
                              type: string
                            status:
                              type: string
                            price:
                              type: number
                            duration:
                              type: string
                            category:
                              type: object
                              properties:
                                id:
                                  type: integer
                                name:
                                  type: string
                            thumbnail_url:
                              type: string
                            lms_id:
                              type: integer
                              description: ID курса в LMS системе
                            student_count:
                              type: integer

  /course/course/view:
    get:
      tags: [Courses]
      summary: Получить детальную информацию о курсе
      description: Возвращает полную информацию о курсе включая программу обучения (только чтение)
      parameters:
        - $ref: './core/common/parameters.yaml#/components/parameters/Id'
      responses:
        '200':
          description: Course details
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                          description:
                            type: string
                          status:
                            type: string
                          price:
                            type: number
                          duration:
                            type: string
                          level:
                            type: string
                            enum: [beginner, intermediate, advanced]
                          category:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                          instructor:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              avatar_url:
                                type: string
                          thumbnail_url:
                              type: string
                          lms_id:
                            type: integer
                            description: ID курса в LMS системе
                          syllabus:
                            type: array
                            description: Программа курса
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                title:
                                  type: string
                                description:
                                  type: string
                                duration:
                                  type: string
                                order:
                                  type: integer
                          requirements:
                            type: array
                            items:
                              type: string
                          outcomes:
                            type: array
                            items:
                              type: string
                          student_count:
                            type: integer
                          rating:
                            type: number
                          reviews_count:
                            type: integer
                          created_at:
                            type: string
                          updated_at:
                            type: string
        '404':
          description: Course not found
          $ref: './core/common/responses.yaml#/components/responses/NotFound'

  # === Page dictionaries (read-only) ===

  /dictionary/dictionary/page-types:
    get:
      tags: [Pages]
      summary: Получить список типов страниц
      description: |
        Справочник типов страниц сайта и продуктов (read-only): landing, blog, help, legal и другие.

        **Назначение:** дать фронтам и внешним CMS нормализованные типы для фильтров и группировки страниц/лендингов.

        **Ключевые особенности:** стабильные коды типов, совместимость с `/dictionary/dictionary/pages`, можно кешировать на клиенте.

        **Пример Use case:** SPA-витрина запрашивает типы, строит фильтры и подсветку меню по категориям страниц.
      responses:
        '200':
          description: Page types list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          items:
                            type: array
                            items:
                              $ref: '#/components/schemas/PageType'
        '400':
          $ref: './core/common/responses.yaml#/components/responses/BadRequest'

  /dictionary/dictionary/pages:
    get:
      tags: [Pages]
      summary: Получить справочник страниц
      description: |
        Доступные страницы сайта (лендинги, продуктовые страницы) с базовыми метаданными (read-only): `title`, `alias`, `type`, `enabled`, SEO-атрибуты.

        **Назначение:** раскрыть структуру публичных и закрытых страниц, чтобы внешние CMS могли собирать меню и лендинги без доступа в админку.

        **Ключевые особенности:** фильтрация по типу (используйте `/dictionary/dictionary/page-types`), статус `enabled`, поля `alias` и `category` для навигации.

        **Пример Use case:** внешняя система заимствует SPA-меню, вызывает `/dictionary/dictionary/pages`, сортирует по типу и обновляет ссылки на новом сайте без внутреннего CMS.
      responses:
        '200':
          description: Pages list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          items:
                            type: array
                            items:
                              $ref: '#/components/schemas/DictionaryPage'
        '400':
          $ref: './core/common/responses.yaml#/components/responses/BadRequest'

  # === Pages ===

  /page/page/index:
    get:
      tags: [Pages]
      summary: Получить список страниц сайта
      description: Возвращает список публичных страниц сайта (только чтение)
      parameters:
        - $ref: './core/common/parameters.yaml#/components/parameters/Page'
        - $ref: './core/common/parameters.yaml#/components/parameters/PerPage'
        - name: type
          in: query
          required: false
          schema:
            type: string
            enum: [landing, blog, help, legal]
          description: Фильтр по типу страницы
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [published, draft]
            default: published
          description: Фильтр по статусу публикации
      responses:
        '200':
          description: List of pages
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                            slug:
                              type: string
                            type:
                              type: string
                            status:
                              type: string
                            excerpt:
                              type: string
                            thumbnail_url:
                              type: string
                            published_at:
                              type: string
                            author:
                              type: object
                              properties:
                                id:
                                  type: integer
                                name:
                                  type: string
                            tags:
                              type: array
                              items:
                                type: string

  /page/page/view:
    get:
      tags: [Pages]
      summary: Получить содержимое страницы
      description: Возвращает полное содержимое страницы с HTML контентом (только чтение)
      parameters:
        - name: slug
          in: query
          required: true
          schema:
            type: string
          description: URL slug страницы или ID
      responses:
        '200':
          description: Page content
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                          slug:
                            type: string
                          content:
                            type: string
                            description: HTML контент страницы
                          excerpt:
                            type: string
                          type:
                            type: string
                          status:
                            type: string
                          seo_title:
                            type: string
                          seo_description:
                            type: string
                          thumbnail_url:
                              type: string
                          published_at:
                            type: string
                          author:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              avatar_url:
                                type: string
                          tags:
                            type: array
                            items:
                              type: string
                          metadata:
                            type: object
                            description: Дополнительные метаданные страницы
                          created_at:
                            type: string
                          updated_at:
                            type: string
        '404':
          description: Page not found
          $ref: './core/common/responses.yaml#/components/responses/NotFound'

components:
  schemas:
    PageType:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: "product-page"

    DictionaryPage:
      type: object
      properties:
        id:
          type: integer
          example: 12
        alias:
          type: string
          example: "product-page-42"
        title:
          type: string
          example: "Курс \"Data Science\""
        description:
          type: string
          example: "Лендинг продукта Data Science"
        enabled:
          type: boolean
          example: true
        type:
          type: string
          description: Тип страницы (используйте справочник page-types)
          example: "course-and-training-promo-page"
