# Integration Reports API - 1 метод
# Отчёты для интеграционных систем (публичный JSON)

openapi: 3.1.0
info:
  title: Integration Reports API
  version: 1.0.0
  description: |
    ## Integration Reports — 1 метод (Сводный JSON)

    Раздел предназначен для отдачи JSON-эквивалента XLSX «Сводный» отчёта. Поддерживает гибкие фильтры по продуктам, группам, прогрессу и профилям пользователей и возвращает список учеников с метаданными.

tags:
  - name: Integration Reports
    description: |
      ## Отчеты для интеграционных систем

      Генерация данных «Сводного» отчёта в JSON для BI/дашбордов без генерации файлов.

paths:
  /v1/integration/report/consolidated:
    post:
      tags: [Integration Reports]
      summary: Сводный отчёт (JSON)
      description: |
        JSON-эквивалент XLSX «Сводный» отчёта с фильтрами по продуктам, группам, прогрессу и полям профиля.

        **Назначение:** отдать тот же набор колонок, что в XLSX «Сводный», но в JSON для BI/дашбордов без генерации файлов.

        **Пример Use case:** BI-интеграция запрашивает данные по конкретным продуктам и отделам, строит графики прогресса и статусов оплат без скачивания XLSX.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: array
                  items:
                    type: integer
                group:
                  type: array
                  items:
                    type: integer
                user_ids:
                  type: array
                  items:
                    type: integer
                progress_from:
                  type: integer
                  minimum: 0
                  maximum: 100
                  default: 0
                progress_to:
                  type: integer
                  minimum: 0
                  maximum: 100
                  default: 100
                fields:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
                  description: Фильтры по полям профиля (username, email, phone, department, position)
                page:
                  type: integer
                  minimum: 1
                  default: 1
                per-page:
                  type: integer
                  minimum: 1
                  maximum: 1000
                  default: 200
                sort:
                  type: string
                  enum: [-date_added, date_added, -progress, progress]
                  default: -date_added
      responses:
        '200':
          description: Отчёт сформирован
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './core/common/schemas.yaml#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          filters:
                            type: object
                          items:
                            type: array
                            items:
                              type: object
                              properties:
                                product:
                                  type: object
                                  properties:
                                    id: {type: integer, example: 59}
                                    title: {type: string, example: "Цифровые коммуникации"}
                                status:
                                  type: object
                                  properties:
                                    code: {type: integer, example: 4}
                                    name: {type: string, example: "Оплачен"}
                                amount:
                                  type: number
                                  example: 60000
                                date_added_at:
                                  $ref: './core/common/schemas.yaml#/components/schemas/DateValue'
                                last_activity_at:
                                  $ref: './core/common/schemas.yaml#/components/schemas/DateValue'
                                registered_at:
                                  $ref: './core/common/schemas.yaml#/components/schemas/DateValue'
                                progress_percent:
                                  type: integer
                                  minimum: 0
                                  maximum: 100
                                user:
                                  type: object
                                  properties:
                                    id: {type: integer}
                                    name: {type: string}
                                    email: {type: string, format: email}
                                    phone: {type: string}
                                    department: {type: string}
                                    position: {type: string}
                          pagination:
                            type: object
                            properties:
                              page: {type: integer, example: 1}
                              per_page: {type: integer, example: 200}
                              total: {type: integer, example: 8}
                              total_pages: {type: integer, example: 1}
              examples:
                sample:
                  summary: Пример успешного ответа
                  value:
                    success: true
                    data:
                      filters:
                        product: [59, 62]
                        progress_from: 50
                        progress_to: 85
                        fields:
                          email: ["ya.ru"]
                      items:
                        - product: {id: 59, title: "Цифровые коммуникации"}
                          status: {code: 4, name: "Оплачен"}
                          amount: 60000
                          date_added_at: {unix: 1730399460, iso: "2024-10-31T13:11:00+03:00"}
                          last_activity_at: {unix: null, iso: null}
                          registered_at: {unix: 1698747060, iso: "2023-10-31T13:11:00+03:00"}
                          progress_percent: 72
                          user:
                            id: 215
                            name: "Георгий"
                            email: "poooga@ya.ru"
                            phone: "+79999999952"
                            department: "Отдел разработки"
                            position: "Директор по продукту"
                      pagination: {page: 1, per_page: 200, total: 8, total_pages: 1}
        '400':
          $ref: './core/common/responses.yaml#/components/responses/BadRequest'
        '403':
          $ref: './core/common/responses.yaml#/components/responses/Forbidden'
