# Common Parameters for Reezonly Space API
components:
  parameters:
    # Pagination parameters
    Page:
      in: query
      name: page
      description: Номер страницы для пагинации
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
        example: 1

    PerPage:
      in: query
      name: per_page
      description: Количество элементов на странице (максимум 100)
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
        example: 50

    Search:
      in: query
      name: search
      description: Поисковый запрос для фильтрации результатов
      required: false
      schema:
        type: string
        example: "ivan"

    # ID parameters
    Id:
      in: query
      name: id
      description: Идентификатор ресурса
      required: true
      schema:
        type: integer
        minimum: 1
        example: 42

    Sort:
      in: query
      name: sort
      description: Сортировка результатов (например, -created_at для обратной сортировки)
      required: false
      schema:
        type: string
        example: "-created_at"

    # Array parameters
    Ids:
      in: query
      name: ids[]
      description: Массив идентификаторов для массовых операций (максимум 100 элементов)
      required: true
      schema:
        type: array
        items:
          type: integer
          minimum: 1
        maxItems: 100
        example: [12, 15, 20]
