# Common Parameters for Reezonly Space API
components:
  parameters:
    # Pagination parameters
    Page:
      in: query
      name: page
      description: Номер страницы для пагинации
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
        example: 1

    PerPage:
      in: query
      name: per-page
      description: Количество элементов на странице (максимум 100)
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
        example: 50

    Search:
      in: query
      name: search
      description: Поисковый запрос для фильтрации результатов
      required: false
      schema:
        type: string
        example: "ivan"

    # ID parameters
    Id:
      in: query
      name: id
      description: Идентификатор ресурса
      required: true
      schema:
        type: integer
        minimum: 1
        example: 42

    PathId:
      in: path
      name: id
      description: Идентификатор ресурса в URL пути
      required: true
      schema:
        type: integer
        minimum: 1
        example: 42

    # Array parameters
    Ids:
      in: query
      name: ids[]
      description: Массив идентификаторов для массовых операций (максимум 100 элементов)
      required: true
      schema:
        type: array
        items:
          type: integer
          minimum: 1
        maxItems: 100
        example: [12, 15, 20]

    # Optional parameters
    ParentId:
      in: query
      name: parent_id
      description: ID родительского элемента (null для корневого уровня)
      required: false
      schema:
        oneOf:
          - type: integer
            minimum: 1
          - type: 'null'
        example: null

    ShowDefault:
      in: query
      name: showDefault
      description: Показать стандартные элементы (0|1)
      required: false
      schema:
        type: integer
        enum: [0, 1]
        default: 0
        example: 1
